language: python
env:
  - TEST_PYCRYPTO="true" TEST_GMPY="true"
  - TEST_PYCRYPTO="false" TEST_GMPY="true"

# Note travis times out with the following:
#  - TEST_PYCRYPTO="true" TEST_GMPY="false"

# In order to test with and without some libraries, we explicitly
# install deps instead of installing from the requirements file

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3-crypto
  - sudo apt-get install -qq libgmp-dev libmpfr-dev
  - sudo apt-get install -qq libgmp3-dev libgmp3c2 libmpfr4 libmpc-dev libmpc2
  - pip install --upgrade pip
  - pip install --upgrade nose
  # Install gmpy2 dependency
  - if [[ $TEST_GMPY == "true" ]]; then
      wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz;
      tar xzvf mpc-1.0.3.tar.gz;
      cd mpc-1.0.3;
      ./configure;
      make;
      sudo make install;
      cd ..;
      pip install gmpy2==2.0.5;
    fi
  # End install gmpy2 dependencies
  - if [[ $TEST_PYCRYPTO == "true" ]]; then
      pip install pycrypto==2.6.1;
    fi
install:
  - pip install numpy
  - pip install click
script:  nosetests -v

